### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by dragonshardz** [SilentChaos512/ExtendedDays#18] opened 2018-03-19 00:27 UTC
Please follow the template for bug reports. Include links to crash reports, if there are any. Feature suggestions and questions may remove all sections.

### Versions

Minecraft Version: 1.12.2
Extended Days Version: 0.2.3-17
Silent Lib Version: 2.16-97

### Expected behavior

World loads

### Actual behaviour

Game crashes

### Steps to reproduce the problem

1. Have the modpack installed: https://minecraft.curseforge.com/projects/disasterpiece-theater-episode-6
2. Make a world
3. Add Extended Days mod 
4. Load the world
5. Game crashes

Crashlog attached
[crash-2018-03-18_17.21.58-client.txt](https://github.com/SilentChaos512/ExtendedDays/files/1823341/crash-2018-03-18_17.21.58-client.txt)

**Comment by SilentChaos512** [comment] 2018-03-20 05:41
Likely caused by the recent Bloodmoon update. I'll get it fixed ASAP.

**Comment by SilentChaos512** [comment] 2018-03-24 15:58
Fixed in latest version. No code changes, just had to build against the latest version of Bloodmoon.

**Closed by SilentChaos512** 2018-03-24 15:58 UTC
Labels: bug
